deis/deisrel

actions/generate_changelog.go
actions/generate_changelog_test.go
actions/generate_changelogs.go
glide.lock
main.go

given a FROM and a TO release, this command will generate an aggregated changelog of all that has
changed from one release to another.
Usage: `deisrel generate-changelog v2.0.0-beta2 v2.0.0-beta3`
To ignore all of the warnings add `2>/dev/null` at the end.
closes #2

feat(actions): add generate-changelog action

---

actions/generate_changelog.go
actions/generate_changelog_test.go

Sometimes contributors tag it with just `doc(` instead of `docs(`.
ping @krancour as he was requesting this feature

feat(actions): add doc( tag for generating changelogs

---

actions/common.go
actions/generate_changelog.go
actions/git.go
actions/git_test.go
actions/helm_generate_e2e.go
main.go

This automates tagging all of the components at their latest SHAs. This can be overridden by
providing a --sha-filepath flag with a path to a file that has the component names and their
respective SHAs, separated by an equals sign.
closes #3

feat(actions): add deisrel git tag command

---

actions/generate_params.go

Relating to https://github.com/deis/workflow/pull/223, this should obviate the need to manually update chart w/ prod value...

feat(generate_params.go): add versionsApiURL to prod for release chart

---

actions/helm_stage_e2e.go

(e2e's pod name also needs the 'dev' -> '$WORKFLOW_RELEASE_SHORT' adjustment for cutting a release chart)

feat(helm_stage_e2e.go): add 'tpl/workflow-e2e-pod.yaml' to list

---

actions/generate_changelog.go
actions/generate_changelog_test.go

Fixes #43 
Sample output (I already had `$GITHUB_ACCESS_TOKEN` in my env):
```console
ENG000656:deisrel aaronschlesinger$ ./deisrel generate-changelog v2.0.0-beta3 v2.0.0-beta4 2> /dev/null
v2.0.0-beta3 -> v2.0.0-beta4
- adb9b43 (minio) - secret: use objectstorage secret for creds than minio user secret
- d4dcc0d (router) - config: move from time_local to time_iso8601
- dce56d5 (router) - config: add application name as part of the log information
- 16f8968 (workflow) - monitoring: Add platform-monitoring docs
- eec2126 (workflow-e2e) - git: curl app endpoint for "Powered by"
- 30e7b2f (builder) - controller: Show the error message from controller instead of resposnse code
- 55f4256 (controller) - deploy: support doing a larger number than 1 in, 1 out deployment
- be4fc6e (controller) - …
```

fix(actions/generate_changelog.go): output the repo for each commit message

---

actions/changelog_util.go
actions/generate_changelog.go
actions/generate_individual_changelog.go
changelog/changelog.go
changelog/changelog_test.go
changelog/single_repo.go
changelog/single_repo_err.go
changelog/single_repo_test.go
changelog/util.go
changelog/util_test.go
git/sha.go
main.go

Fixes #45 
TODO:
Sample output:
```console
ENG000656:deisrel aaronschlesinger$ GITHUB_TOKEN=$GITHUB_ACCESS_TOKEN ./deisrel changelog individual builder v2.0.0-beta3 8215d19 v2.0.0-beta4 2> /dev/null
v2.0.0-beta3 -> v2.0.0-beta4
- 30e7b2f controller: Show the error message from controller instead of resposnse code
- eacaf38 git-push: handle the errors during git push
- 8e9de01 cleaner: remove the usage of watch api
- 9cc7852 gitreceive: ignore error if `git gc` fails
- d64b400 CHANGELOG.md: update for v2.0.0-beta3
- d8fe502 badge: added code-beat badge
- 142b0b7 CHANGELOG.md: add entry for beta4
- 6441ece Makefile: update go-dev to 0.11.1
```

feat(main.go,actions): add command to generate a changelog entry for an individual repo

---

Makefile
actions/get_shas.go
actions/git.go
actions/helm_generate.go
actions/helm_generate_test.go
actions/helm_stage.go
actions/helm_stage_test.go
main.go

So that the commit shas returned from a given repo can be from a
specific ref (SHA or branch) as opposed to default of master...
If your change requires any additions or changes to the [Release Checklist](https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md), please submit them as 1 or more pull requests against that repo and refer to them here.
Ref deis/workflow#1234
Ref deis/workflow#5678

feat(getShas): add ability to pass in ref to git shas cmd

---

actions/get_shas.go
actions/git.go
main.go

`./deisrel git tag` didn't previously allow the use of a `--ref <branch or sha>` flag.  This change enables passing the flag

fix(get_shas.go): ref wasn't getting to get shas method

---

actions/helm_stage_test.go
actions/release_walker.go

As workflow-dev(-e2e) charts have had their version metadata
updated from `v2-beta` to `v2.0.0`
Ref https://github.com/deis/charts/pull/281

chore(actions/release_walker.go): update version string change

---

Makefile

Fixes https://github.com/deis/deisrel/issues/92
Please see #92 for an explanation on what this fixes
None required

fix(Makefile): store versioned distribution builds in a subfolder of the bin dir

---

actions/common.go
actions/helm_stage.go

As location of e2e pod name will have changed in https://github.com/deis/charts/pull/299.
Therefore, this PR depends on https://github.com/deis/charts/pull/299 being merged.

chore(actions/common.go): update filename for e2e chart

---

actions/common.go
actions/docker/cmd.go
actions/docker/retag.go
actions/git.go
docker/client.go
docker/cmd_client.go
docker/image.go
docker/image_tag_pair.go
docker/image_tag_pair_test.go
docker/image_test.go
docker/memory_client.go
docker/pull.go
docker/pull_test.go
docker/push.go
docker/push_test.go
docker/retag.go
docker/retag_test.go
docker/sdk_client.go
git/create_tags_test.go
git/get_shas.go
git/move_milestones.go
git/repo_and_sha.go
git/repo_and_sha_list.go
git/repo_names.go
git/sha.go
git/shas_from_filepath.go
glide.lock
glide.yaml
main.go

Fixes https://github.com/deis/deisrel/issues/57
Fixes https://github.com/deis/deisrel/issues/6
Fixes https://github.com/deis/deisrel/issues/58
https://github.com/deis/workflow/pull/355

feat(main.go,actions): create a docker image tagging command

---

actions/docker/cmd.go
actions/docker/retag.go
docker/image.go
docker/image_test.go

Fixes #107 
Adds a new `--registries` flag, which can be specified multiple times, to indicate all of the docker registries that the caller would like to pull from. For example:
```console
./deisrel docker retag --yes=false --ref=v2.0.0 --registries="index.docker.io" --registries="quay.io" workflow-2.1.0
```
None required. This change will automatically pull from, tag and push to both quay.io and the docker hub

fix(actions,docker): allowing tag & push to multiple registries

---

actions/branches/cmd.go
actions/branches/create.go
docker/push_test.go
git/create_branches.go
git/create_branches_test.go
git/ref.go
git/ref_test.go
main.go

Fixes #99 
TODO: 
Usage:
```console
ENG000656:deisrel aaronschlesinger$ ./deisrel branches create --name="test" --yes=false --ref="master"
Getting SHAs for all repositories on 'master'
postgres - f745e74d620a8d1847da20be8d6221aeaa8ea4c4
stdout-metrics - c37e3ec5390222e5f773ad2a7b4fc19cd0ca23f2
controller - c65c5083104780c3d7c5993a23dc7fdb9b2bf4b9
builder - a0905cc68aaae32d1f3c52da9ced33deed1a84ec
fluentd - 0c5dc2146bdb2c11691778ddece38d6a53e9c629
workflow-manager - af9ef041b2b04cb013e7c7d659a85af478048ea2
registry - 8528182f7785489cdf1e257faa2deaf0878b9f22
minio - ba66283177efd6f98cb665e44c4b565e2dc35896
slugrunner - 624d8a38ef0b2cceb5d9b7908d81ec602900f732
workflow-e2e - 08d5322607cbf8bef7dad9bcd8ae1cecf5b616e0
monitor - 14d6af08d14188b2b08f9d280b5a5cdffa00aca5
logger - …
```

feat(main.go,git,actions): add GH create branches command

---

actions/common.go

so that git operations related to a release are also done for this repo
This is also necessary so that the https://ci.deis.io/job/workflow-cli-tag-release/ job receives the tag push event for it to run.

chore(common.go): add workflow-cli to additional git repos

---

components/components.go

Fixes #125 
Annotated tags have their own SHA, so comparing the SHA of an annotated tag to master will always be dirty.
cc @mboersma

fix(git): handle annotated tags properly

---

Makefile

Includes the go 1.7 toolchain. See https://tip.golang.org/doc/go1.7.

chore(Makefile): update to go-dev 0.17.0

---

actions/generate_individual_changelog.go

Sends the "Creating changelog..." message to `os.Stderr` so it can be filtered from the actual CHANGELOG content in automation scripts.
```bash
$ ./deisrel changelog individual logger v2.3.2
skipping commit 99da2805ec8dcd87dcd508887d7faf5824502a07
Creating changelog for logger with tag v2.3.1 through commit 99da2805ec8dcd87dcd508887d7faf5824502a07
- [`e36fe0f`](https://github.com/deis/logger/commit/e36fe0f4e0dcafa7376a3fb6c35e597c3c0b3e43) CHANGELOG: remove CHANGELOG
$ ./deisrel changelog individual logger v2.3.2 2> /dev/null
- [`e36fe0f`](https://github.com/deis/logger/commit/e36fe0f4e0dcafa7376a3fb6c35e597c3c0b3e43) CHANGELOG: remove CHANGELOG
```
Closes #135.

fix(actions): send "Creating changelog" message to stderr

---

README.md
main.go

The token is (almost) mandatory, and this env var is more standard than `GH_TOKEN`.
Closes #144.

fix(main.go): require `GITHUB_ACCESS_TOKEN` to be set

---

actions/generate_changelog.go
actions/generate_changelog_err.go
changelog/changelog.go
changelog/changelog_test.go
changelog/single_repo_err.go
main.go

To compensate for individual components now following their own release cadences.
**Notes:** 
* this goes back to the changelog format used in `v2.0.0`-`v2.3.0` Workflow releases such as [v2.2.0](https://deis.com/docs/workflow/changelogs/v2.2.0/) (with the addition of alphabetical ordering!) as opposed to the more recent/manually assembled format as seen in the latest [v2.8.0 release](https://deis.com/docs/workflow/changelogs/v2.8.0/)
* since the `deisrel changelog global` command now takes the previous Workflow release's `generate_params.toml` (for discerning each component's version migration) and as that file does not contain info on the `workflow`, `workflow-cli` and `workflow-e2e` repos, we are unable to add changelog entries with the code as it is now.  (Would welcome ideas on how …

ref(*): fix changelog global command

---

actions/generate_individual_changelog.go
changelog/single_repo.go

Currently via `--show-skipped-commits` flag.  
However, I might also propose we go further and remove this new option and just show the full skipped changelog message as a default -- I find it helps to be sure all skipped commits indeed should not be included.  
For example, compare the two (original sha-only format first):
```
$ ./deisrel changelog individual workflow unknown
skipping the following commits:
- 6f1c46686e889d0f09af5878fa924577db5d3351
- 027509f3fb79904dbe9c974357e3c97a711fc077
- 1d70f53f1748981e7aa40e71948cdd76b56b53ca
- 6a620266d3e160a53d9a3278f9e01f818dad9d7e
- 3b5069dfde8ed7cc448a45825401549a14b5ad4a
- f2f270b486ab9b64ca7c71188b22365a9fd55d1a
- bc54566d6b9167191301cf2e8f05fc0ab1ec7324
- 5c52d0430604c3149fd382252a9bd9121dbe32b3
...
```
```
$ ./deisrel changelog …
```

feat(*): show skipped commits in full changelog format

---

changelog/single_repo.go
changelog/single_repo_test.go

...instead of instantiating a new one each time appendToValues is invoked!

fix(single_repo.go): pass in skippedCommits slice

---

README.md
actions/generate_changelog.go
map.json

For the Workflow repo itself (anticipated changelog) and auxiliary
repos such as `workflow-cli` and `workflow-e2e` (assumed to already be released)
The default/happy case test would be:
```
$ make build
$ # simulate last release
$ export WORKFLOW_RELEASE=v2.11.0 WORKFLOW_PREV_RELEASE=v2.10.0
$ helm repo add workflow https://charts.deis.com/workflow # if haven't done so already
$ helm fetch --untar workflow/workflow --version v2.10.0
$ # verify generated changelog shows workflow(-cli,-e2e) changes:
$ ./deisrel changelog global workflow/requirements.lock map.json
```
There haven't been any commits in deis/workflow since this last `v2.11.0` release, but if there were, they would be seen in the following simulated upcoming release:
```
$ # simulate upcoming release
$ export …
```

feat(generate_changelog.go): add changelog entries
