deis/deisrel

- _scripts/ci/bintray-template.json
`"subject"` needs to be `'deis'` in bintray template
> fix(bintray-template.json): subject change to 'deis'

- actions/common.go
- actions/helm_stage.go
- main.go
> chore(RELEASE vars): update DEIS -> WORKFLOW

- actions/generate_changelog.go
- actions/get_shas.go
- actions/git.go
- actions/helm_generate_e2e.go
- actions/helm_generate_workflow.go
- actions/helm_stage_e2e.go
- actions/helm_stage_workflow.go
> fix(*): update action func to adhere to codegangsta 1.15.0 spec

- actions/generate_params.go
- actions/generate_params_e2e.go
- actions/helm_generate.go
- actions/helm_generate_e2e.go
- actions/helm_generate_test.go
- actions/helm_generate_workflow.go
- main.go
workflow-e2e `helm-params` still needed some love, also defaulting `--org` to `deisci`
> fix(helm_generate e2e): fix helm generate e2e files

- main.go
> fix(main.go): change GITHUB_TOKEN to GITHUB_ACCESS_TOKEN

- README.md
> docs(README): document deisrel

- actions/generate_params.go
ref https://github.com/deis/charts/pull/268
cc @arschles 
If your change requires any additions or changes to the [Release Checklist](https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md), please submit them as 1 or more pull requests against that repo and refer to them here.
Ref deis/workflow#1234
Ref deis/workflow#5678
> chore(generate_params.go): set default doctor api url to prod

- actions/helm_stage_test.go
- actions/release_walker.go
> fix(actions/release_walker.go): fix issue where /dev/null was changed

- actions/helm_stage_test.go
- actions/release_walker.go
enables deisrel to update `workflow-dev` [version](https://github.com/deis/charts/blob/master/workflow-dev/Chart.yaml#L3) and `workflow-dev-e2e` [version](https://github.com/deis/charts/blob/master/workflow-dev-e2e/Chart.yaml#L3)
> feat(release_walker.go): update version as well

- actions/common.go
- actions/generate_changelog.go
- actions/generate_changelog_test.go
- actions/git.go
> feat(git tag/changelog): also include non-Workflow-chart repo names

- README.md
Ref https://github.com/deis/workflow/issues/285
> docs(README.md): remove beta status

- changelog/single_repo.go
- changelog/single_repo_test.go
> fix(changelog/single_repo.go): sha text now links to commit

- .travis.yml
- Makefile
No associated documentation - this is a patch only to enhance local deisrel development.
Fixes #40
> fix(.travis.yml,Makefile): add host-native build and test Makefile targets

- actions/git.go
- actions/repo_and_sha.go
- actions/repo_and_sha_list.go
- actions/repo_and_sha_list_test.go
- actions/repo_and_sha_test.go
This patch changes an implementation detail but no external interface details, so no documentation changes are needed.
Fixes #38
> fix(actions): print repositories in alphabetical order on git tag

- Makefile
> feat(build): Limit cross-compilation to darwin/amd64 and linux/amd64

- actions/helm_stage_test.go
- actions/release_walker.go
Ref deis/workflow#296
Fixes #85
> fix(helm-stage): amend helm-stage to work with major release

- actions/common.go
- actions/generate_params.go
ref https://github.com/deis/charts/pull/294
> chore(actions/common.go,generate_params.go): remove stdout-metrics

- actions/common.go
- actions/move_milestones.go
- git/move_milestones.go
- git/move_milestones_test.go
- main.go
~~This isn't done just yet, but I am PR'ing my in-progress work so that @arschles can see where I am headed and stop me sooner than later if I'm missing the mark.~~
> feat(git): Add bulk reassignment of issues and PRs from one milestone to another

- actions/docker/retag.go
- docker/image.go
instead of manually shortening the SHA in the docker package
None
> fix(actions,docker): use git short sha transform

- actions/generate_params.go
- git/repo_names.go
This is necessary until #12 is done.
> chore(repos): Add nsq; remove stdout-metrics

- git/repo_names.go
redis is a new component in logging infrastructure which will be a part of release process from now on
> feat(redis): add redis component to deisrel

- components/components.go
> fix(components): check if component exists in chart before trying to read it

- actions/generate_individual_changelog.go
- main.go
```
./deisrel changelog individual workflow-cli v2.3.0
skipping commit 70df6e0b756798e3e5eec0c7192739a02768194b
skipping commit 2b35225474135a56e13b9052563eb64f45ec1258
skipping commit 75c43e75d3550cf47989c48ede02c7ef3fc8765c
skipping commit 44f50850118d77553a5ec63181ec888f3549a4e2
skipping commit 76b60b584704d325c933726061182f8c12966c34
skipping commit 072ef3062049108c1995da6ffd8cbfc5fc1d2346
skipping commit ac06c69d01466abeea9d43aad1a3ee445572067b
skipping commit 0a66819b2d1fe49aff419f44fe7e05b9fda638bf
Creating changelog for workflow-cli with tag v2.2.0 through commit 0a66819b2d1fe49aff419f44fe7e05b9fda638bf
- [`5615bb4`](https://github.com/deis/workflow-cli/commit/5615bb40c59ee68217631132b49c731efe8f6a6e) ci: send emails to slack on e2e failure (#133)
- …
```
> feat(changelog): assume tag and sha options

- README.md
Updates the JSON blob to reflect what we've been using for the v2.4.0 release process.
> docs(README.md): update list of components

- changelog/changelog.go
- changelog/changelog_test.go
- changelog/single_repo.go
> feat(changelog): add test/tests category to changelog

- actions/release_component.go
- actions/release_component_test.go
- glide.lock
- main.go
> feat(release_component): automate component releases

- Makefile
See https://github.com/deis/docker-go-dev/releases/tag/0.20.0
> chore(Makefile): update go-dev to 0.20.0

- actions/release_component.go
Not sure how we can manually test this one since it is reliant on the github API
fixes #149
> fix(component_release): set CreatedAt and PublishedAt to time.Now()

- README.md
- actions/generate_changelog.go
- components/components.go
- glide.lock
- glide.yaml
- main.go
Closes #151 
TODO
To test:
At minimum, run base `deisrel` command and `deisrel changelog global` command with args as mentioned in updated `README`.
> ref(*): update for use with Kubernetes Helm

- changelog/changelog.go
Fixes https://github.com/deis/deisrel/issues/136
> fix(changelog.go): fix spacing

- actions/release_component.go
- actions/release_component_test.go
- testutil/test_server.go
Fixes https://github.com/deis/deisrel/issues/143
> tests(release_component.go): add createRelease test
